### ISSUE TITLE
Cannot install on Debian

### ISSUE THREAD

**Issue by shaneken** [controlx-io/logic-prover-support#1]
Hi,
I wanted to try using it on my spare computer with Debian 9 and had an issue. When I double clicked the downloaded file `plc-logic-prover-linux-0.1.8.AppImage` it opens "Open With" dialog.
How can I install it?

Thanks,
Shane

**Comment by alex-controlx** [comment]
@shaneken working on Linux a bit tricky. AppImage files are not required to be installed. It is a self containing package.
When you download the app it is not executable. Make it executable by following the next steps: Right click on downloaded file > _Properties_ > _Permission_ tab > Check "Allow executing file as program". Now it is executable, but there is one more step.

Enable the user namespaces feature. It is required for this type of software packages. In terminal run: `sudo sysctl kernel.unprivileged_userns_clone=1` 

Also you can rename and move the file where you want. It will still open your current project.

**Comment by alex-controlx** [comment]
Hi @shaneken how did you go? Have you managed to install it?

**Comment by alex-controlx** [comment]
@shaneken , I'm closing the issue down. Feel free to reopen if still have the problem.

**Comment by shaneken** [comment]
yeah, it's all good. Using Windows version.
