### ISSUE TITLE
Error: WS1: There is no parent to save this Action Unit.

### ISSUE THREAD

**Issue by alex-controlx** [controlx-io/logic-prover-support#2]
To replicate the error:
- Click **Duplicate** Action Unit
- In the same Action Unit click **Move to**
- Change _Name_
- Click **Save** button

Result:
- No changes saved on **Save** button click

Expectation:
- No error and change saved on **Save** button click

Workaround:
After Duplicate and Move To click on another Action Unit. Come back to the duplicated Action Unit and Save it after changes.

**Comment by alex-controlx** [comment]
Fixed in release v0.1.15

**Comment by beingmerry** [comment]
Is this program still in active development? I'm interested in trying this out sometime soon. Also I think this issue can be closed.

**Comment by alex-controlx** [comment]
Unfortunately, it is not. We work on too many smaller projects and different PLCs so full logic testing isn't justifiable anymore. I'm planning to open source it so anyone can contribute.
